% noise = [0.125 0.25 0.5 1 1.5];
% trial = [9 6 3 8 8];

noise = 0;
trial = 7;

for i=1:length(noise)
    for time = [3 17 55]

        fig = openfig(sprintf('./figures/%.2f_%d_%d.fig',noise(i),trial(i),time+1));

    %     fig = gcf;
        our = fig.Children(1);
        hoff = fig.Children(2);

        figure(100)
        clf
        set(our,'parent',gcf)

        set(gcf,'Units','inches',...
        'Position',[2 2 4 4],...
        'PaperPositionMode','auto');

        box on
        hold on
        plot([0 40 40 0 0], [0 0 40 40 0],'--','Color',[0.75, 0.75, 0])

        xlabel('x [m]')
        ylabel('y [m]')
        axis([-5 45 -5 45])
        set(gca,...
            'Units','normalized',...
            'YTick',0:10:40,...
            'XTick',0:10:40,...
            'Position',[.115 .125 .88 .87],...
            'FontUnits','points',...
            'FontWeight','bold',...
            'FontSize',12,...
            'FontName','Times')

        pos = get(gcf,'Position');
        set(gcf,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])

        print(sprintf('./figures/our_%03.f_%d.pdf',noise(i)*100,time),'-dpdf','-painters')

        clf
        set(hoff,'parent',gcf)

        set(gcf,'Units','inches',...
        'Position',[2 2 4 4],...
        'PaperPositionMode','auto');

        box on
        hold on
        plot([0 40 40 0 0], [0 0 40 40 0],'--','Color',[0.75, 0.75, 0])

        xlabel('x [m]')
        ylabel('y [m]')
        axis([-5 45 -5 45])
        set(gca,...
            'Units','normalized',...
            'YTick',0:10:40,...
            'XTick',0:10:40,...
            'Position',[.115 .125 .88 .87],...
            'FontUnits','points',...
            'FontWeight','bold',...
            'FontSize',12,...
            'FontName','Times')

        pos = get(gcf,'Position');
        set(gcf,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])

        print(sprintf('./figures/hoff_%03.f_%d.pdf',noise(i)*100,time),'-dpdf','-painters')
    end
end

% print -dpdf -painters test.pdf
% print -deps2 test.eps



% ylabel({'$y(t)$'},...
% 'FontUnits','points',...
% 'interpreter','latex',...
% 'FontSize',9,...
% 'FontName','Times')
% xlabel('Time(s)',...
% 'FontUnits','points',...
% 'FontWeight','normal',...
% 'FontSize',7,...
% 'FontName','Times')

% legend({'$y=\sin(t)$'},...
% 'FontUnits','points',...
% 'interpreter','latex',...
% 'FontSize',7,...
% 'FontName','Times',...
% 'Location','NorthEast')
% title('Sinusoidal function',...
% 'FontUnits','points',...
% 'FontWeight','normal',...
% 'FontSize',7,...
% 'FontName','Times')

% ax = gca;
% outerpos = ax.OuterPosition;
% ti = ax.TightInset; 
% left = outerpos(1) + ti(1);
% bottom = outerpos(2) + ti(2);
% ax_width = outerpos(3) - ti(1) - ti(3);
% ax_height = outerpos(4) - ti(2) - ti(4);
% ax.Position = [left bottom ax_width ax_height];
